require('./app/app');
require('./app/pages/Portfolio/animations');
require('./app/pages/Portfolio/AudioPlayer');
require('./assets/audio/mario.mp3');
require('./assets/audio/how-you-like-that.mp3');
require('./assets/audio/everything-i-wanted.mp3');
require('./assets/audio/ice-cream.mp3');
require('./assets/audio/single.mp3');
require('./assets/audio/let-go-for-tonight.mp3');
require('./assets/img/how_you_like_that.jpg');
require('./assets/img/everything_i_wanted.jpg');
require('./assets/img/ice_cream.jpg');
require('./assets/img/single.jpg');
require('./assets/img/let_go_for_tonight.jpg');
require('./app/pages/Portfolio/progressBar');
import './styles.scss';
